package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
	"voiceline-mvp/models" // Adjust the import path if necessary
)

// CreateNote sends the formatted HTML summary as a Note to HubSpot
// and associates it with the respective contact.
func CreateNote(htmlBody string) error {
	token := os.Getenv("HUBSPOT_TOKEN")
	contactID := os.Getenv("HUBSPOT_CONTACT_ID")

	if token == "" || contactID == "" {
		return fmt.Errorf("HUBSPOT_TOKEN or HUBSPOT_CONTACT_ID is missing in the .env file")
	}

	// 1. Construct the JSON payload for the HubSpot Note
	reqBody := models.HubSpotNoteRequest{
		Properties: models.NoteProperties{
			Timestamp: fmt.Sprintf("%d", time.Now().UnixMilli()),
			Body:      htmlBody,
		},
		Associations: []models.Association{
			{
				To: models.AssociationTo{ID: contactID},
				Types: []models.AssocType{
					{
						AssociationCategory: "HUBSPOT_DEFINED",
						AssociationTypeId:   202, // HubSpot internal ID for Note-to-Contact association
					},
				},
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf("error marshaling JSON: %w", err)
	}

	// 2. Send the HTTP POST request to HubSpot
	url := "https://api.hubapi.com/crm/v3/objects/notes"
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return fmt.Errorf("error creating the HTTP request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("error executing HubSpot API call: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		return fmt.Errorf("hubspot API error, status code: %d", resp.StatusCode)
	}

	return nil
}

// CreateTask creates a scheduled action item in HubSpot
// and associates it with the respective contact.
func CreateTask(task models.Task) error {
	token := os.Getenv("HUBSPOT_TOKEN")
	contactID := os.Getenv("HUBSPOT_CONTACT_ID")

	// 1. Parse the "YYYY-MM-DD" date from OpenAI into milliseconds (HubSpot's required format)
	parsedTime, err := time.Parse("2006-01-02", task.DueDate)

	// Default fallback: Use current time if AI failed to provide a valid date
	timestampMs := fmt.Sprintf("%d", time.Now().UnixMilli())
	if err == nil {
		timestampMs = fmt.Sprintf("%d", parsedTime.UnixMilli())
	}

	// 2. Construct the Task payload (including the timestamp)
	reqBody := models.HubSpotTaskRequest{
		Properties: models.TaskProperties{
			Timestamp: timestampMs, // Required by HubSpot to validate the task creation
			Subject:   fmt.Sprintf("[%s] %s", task.DueDate, task.Title),
			Status:    "NOT_STARTED",
			Body:      "Automatically generated by Voiceline AI",
		},
		Associations: []models.Association{
			{
				To: models.AssociationTo{ID: contactID},
				Types: []models.AssocType{
					{AssociationCategory: "HUBSPOT_DEFINED", AssociationTypeId: 204}, // Task-to-Contact ID
				},
			},
		},
	}

	jsonData, _ := json.Marshal(reqBody)
	req, _ := http.NewRequest("POST", "https://api.hubapi.com/crm/v3/objects/tasks", bytes.NewBuffer(jsonData))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)

	if err != nil {
		return fmt.Errorf("http error while creating task: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		// Read and return the error body for easier debugging (e.g., missing properties)
		bodyBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("hubspot API error (Status %d): %s", resp.StatusCode, string(bodyBytes))
	}

	return nil
}

// UpdateContact patches the CRM contact properties based on the AI extraction.
func UpdateContact(updates models.ContactUpdates) error {
	token := os.Getenv("HUBSPOT_TOKEN")
	contactID := os.Getenv("HUBSPOT_CONTACT_ID")

	// 1. Build a dynamic property map: We only update fields that the AI actually extracted!
	props := make(map[string]string)

	if updates.LeadStatus != "" {
		props["hs_lead_status"] = updates.LeadStatus
	}
	if updates.LifecycleStage != "" {
		props["lifecyclestage"] = updates.LifecycleStage
	}
	if updates.Revenue != "" {
		props["annualrevenue"] = updates.Revenue
	}
	if updates.Industry != "" {
		props["industry"] = updates.Industry
	}

	// If the AI didn't find any relevant contact data, skip the API call to save rate limits
	if len(props) == 0 {
		return nil
	}

	// 2. Construct the Contact Patch payload
	reqBody := models.HubSpotContactPatch{
		Properties: props,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf("error marshaling JSON for contact patch: %v", err)
	}

	// 3. Send the PATCH request to update the contact
	url := fmt.Sprintf("https://api.hubapi.com/crm/v3/objects/contacts/%s", contactID)
	req, err := http.NewRequest("PATCH", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return fmt.Errorf("error creating contact patch request: %v", err)
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("http error during contact update: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		// Read the error body if HubSpot rejects a property value (e.g., invalid enum like QUALIFIED)
		bodyBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("hubspot API error (Status %d): %s", resp.StatusCode, string(bodyBytes))
	}

	return nil
}
